#!/usr/bin/env bash

# Load rust config vars
source "$HOME/.cargo/env"

# Build function
build () {
    cargo build --release -Z build-std=core,alloc --target powerpc-unknown-eabi.json
}

# Run script
echo "Initial build, just to be safe."
build
echo "Done! Build watch started."
inotifywait -mq -r -e create -e modify -e delete -e move ./source |
    while read dir action file; do
        echo "The file '$file' appeared in directory '$dir' via '$action', rebuilding..."
        build
    done
