#!/usr/bin/env bash
export PUID=$(id -u)
export PGID=$(id -g)

# get the xdg runtime dir
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

# Set the emulator config.
cp Dolphin.ini emulator/config/Dolphin.ini

docker-compose up